import { Food } from '../shared/models/Food';

const allPizza: Food[] = [
  {
    id: '65f8db88d971385921ae1fa9',
    name: 'Classic Margherita Pizza',
    cookTime: '10-15',
    price: 10,
    favorite: false,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'assets/margherita.webp',
    tags: ['Classic', 'Vegetarian', 'Lunch', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1faa',
    name: 'Pepperoni Feast Pizza',
    price: 12,
    cookTime: '15-20',
    favorite: true,
    origins: ['United States'],
    stars: 4.7,
    imageUrl: 'assets/pepperoni.webp',
    tags: ['Meat Lovers', 'FastFood', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fab',
    name: 'BBQ Chicken Pizza',
    price: 14,
    cookTime: '15-20',
    favorite: false,
    origins: ['United States'],
    stars: 4.2,
    imageUrl: 'assets/bbq-chicken.webp',
    tags: ['BBQ', 'Chicken', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fac',
    name: 'Vegetarian Supreme Pizza',
    price: 11,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.4,
    imageUrl: 'assets/vegetarian-supreme.webp',
    tags: ['Vegetarian', 'Supreme', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fad',
    name: 'Hawaiian Pizza',
    price: 12,
    cookTime: '15-20',
    favorite: false,
    origins: ['Canada'],
    stars: 4.3,
    imageUrl: 'assets/hawaiian.jpeg',
    tags: ['Pineapple', 'Ham', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fae',
    name: 'Mediterranean Veggie Pizza',
    price: 13,
    cookTime: '15-20',
    favorite: false,
    origins: ['Greece'],
    stars: 4.6,
    imageUrl: 'assets/mediterranean-veggie.webp',
    tags: ['Vegetarian', 'Mediterranean', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1faf',
    name: 'Four Cheese Pizza',
    price: 12,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.6,
    imageUrl: 'assets/four-cheese.webp',
    tags: ['Cheese', 'Vegetarian', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fb0',
    name: 'Buffalo Chicken Pizza',
    price: 14,
    cookTime: '15-20',
    favorite: false,
    origins: ['United States'],
    stars: 4.5,
    imageUrl: 'assets/buffalo-chicken.webp',
    tags: ['Buffalo', 'Chicken', 'Spicy', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fb1',
    name: 'Supreme Meat Pizza',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['United States'],
    stars: 4.8,
    imageUrl: 'assets/supreme-meat.webp',
    tags: ['Meat', 'Supreme', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fb2',
    name: 'Barbecue Bacon Pizza',
    price: 13,
    cookTime: '15-20',
    favorite: false,
    origins: ['United States'],
    stars: 4.4,
    imageUrl: 'assets/barbecue-bacon.webp',
    tags: ['BBQ', 'Bacon', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fb3',
    name: 'Veggie Delight Pizza',
    price: 11,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.3,
    imageUrl: 'assets/veggie-delight.webp',
    tags: ['Vegetarian', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fb4',
    name: 'Spicy Sausage Pizza',
    price: 13,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'assets/spicy-sausage.webp',
    tags: ['Spicy', 'Sausage', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fb5',
    name: 'White Pizza',
    price: 12,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.6,
    imageUrl: 'assets/white-pizza.webp',
    tags: ['Vegetarian', 'Garlic', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fb6',
    name: 'Pesto Chicken Pizza',
    price: 14,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.7,
    imageUrl: 'assets/pesto-chicken.webp',
    tags: ['Pesto', 'Chicken', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fb7',
    name: 'Sicilian Pizza',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.8,
    imageUrl: 'assets/sicilian.webp',
    tags: ['Sicilian', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fb9',
    name: 'Italian Sausage Pizza',
    price: 13,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'assets/italian-sausage.webp',
    tags: ['Italian', 'Sausage', 'Dinner'],
  },
  {
    id: '65f8db88d971385921ae1fba',
    name: 'Mushroom Lover Pizza',
    price: 11,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.3,
    imageUrl: 'assets/mushroom-lover.webp',
    tags: ['Mushroom', 'Vegetarian', 'Dinner'],
  },

  {
    id: '65f8db88d971385921ae1fbc',
    name: 'Artichoke Pizza',
    price: 12,
    cookTime: '15-20',
    favorite: false,
    origins: ['Italy'],
    stars: 4.4,
    imageUrl: 'assets/artichoke.webp',
    tags: ['Artichoke', 'Vegetarian', 'Dinner'],
  },
];

export default allPizza;
